# Note: I'm going with a versioning-strategy of "increase" so that Dependabot will update pyproject.toml when
# an older version is known to have an issue. If this has any bad side effects, please switch it back to "auto".
# Documentation at https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#versioning-strategy--

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"

