configfile: "config.yaml"


include: "src/snakefiles/datacollect.snakefile"
include: "src/snakefiles/anatomy.snakefile"
include: "src/snakefiles/cell_line.snakefile"
include: "src/snakefiles/gene.snakefile"
include: "src/snakefiles/protein.snakefile"
include: "src/snakefiles/geneprotein.snakefile"
include: "src/snakefiles/diseasephenotype.snakefile"
include: "src/snakefiles/process.snakefile"
include: "src/snakefiles/chemical.snakefile"
include: "src/snakefiles/drugchemical.snakefile"
include: "src/snakefiles/taxon.snakefile"
include: "src/snakefiles/genefamily.snakefile"
include: "src/snakefiles/leftover_umls.snakefile"
include: "src/snakefiles/macromolecular_complex.snakefile"
include: "src/snakefiles/publications.snakefile"
include: "src/snakefiles/duckdb.snakefile"
include: "src/snakefiles/reports.snakefile"
include: "src/snakefiles/exports.snakefile"


# Some general imports.
import shutil
from src.snakefiles import util
from src.snakefiles.util import get_all_compendia, write_done

# Some global settings.
import os

os.environ["TMPDIR"] = config["tmp_directory"]


# Trivial done-marker rules and destructive cleanup rules run locally so they don't consume a SLURM slot.
localrules:
    all,
    all_outputs,
    clean_compendia,
    clean_downloads,


# Top-level rules.
rule all:
    input:
        # See rule all_outputs later in this file for how we generate all the outputs.
        config["output_directory"] + "/reports/outputs_done",
        # reports_done are generated by the rules in src/snakefiles/
        config["output_directory"] + "/reports/reports_done",
        # Build all the Parquet files.
        config["output_directory"] + "/duckdb/done",
        # Build all the DuckDB (index-wide) reports.
        config["output_directory"] + "/reports/duckdb/done",
        # Build all the exports.
        config["output_directory"] + "/kgx/done",
        config["output_directory"] + "/sapbert-training-data/done",
        # Store the config.yaml file used to produce the output.
        config_file="config.yaml",
    output:
        x=config["output_directory"] + "/reports/all_done",
        output_config_file=config["output_directory"] + "/config.yaml",
    run:
        shutil.copyfile(input.config_file, output.output_config_file)
        write_done(output.x)


rule all_outputs:
    input:
        config["output_directory"] + "/reports/anatomy_done",
        config["output_directory"] + "/reports/chemicals_done",
        config["output_directory"] + "/reports/disease_done",
        config["output_directory"] + "/reports/gene_done",
        config["output_directory"] + "/reports/genefamily_done",
        config["output_directory"] + "/reports/geneprotein_done",
        config["output_directory"] + "/reports/process_done",
        config["output_directory"] + "/reports/protein_done",
        config["output_directory"] + "/reports/taxon_done",
        config["output_directory"] + "/reports/cell_line_done",
        config["output_directory"] + "/reports/umls_done",
        config["output_directory"] + "/reports/macromolecular_complex_done",
        config["output_directory"] + "/reports/drugchemical_done",
        config["output_directory"] + "/reports/publications_done",
    output:
        x=config["output_directory"] + "/reports/outputs_done",
    run:
        write_done(output.x)


rule clean_compendia:
    params:
        dir=config["output_directory"],
    shell:
        "rm {params.dir}/compendia/*; rm {params.dir}/synonyms/*"


rule clean_downloads:
    params:
        dir=config["download_directory"],
    shell:
        "rm -rf {params.dir}/*"


# Sometimes a synonyms file is available as a .gz file, but not as the .txt file itself.
# This rule is here so that Snakemake knows how to uncompress it if needed.
rule uncompress_synonym_file:
    input:
        config["output_directory"] + "/synonyms/{synonym_file}.txt.gz",
    output:
        config["output_directory"] + "/synonyms/{synonym_file}.txt",
    benchmark:
        config["output_directory"] + "/benchmarks/uncompress_synonym_file_{synonym_file}.tsv"
    shell:
        "gunzip {input} -c > {output}"


# Compendia are distributed as .txt.gz. Unlike a synonyms file -- which has exactly one consumer,
# its own semantic type's rule, and so is compressed there -- a compendium is read by jobs across
# the pipeline (DuckDB/Parquet export, KGX export, leftover_umls, both conflations, and the
# per-compendium content reports). So compression gets its own rule, gated behind all of them.
#
# The compendia .txt are temp(), so Snakemake deletes each one as soon as its last consumer job
# finishes. Because this rule is gated last, that is immediately after compression, and the two
# copies never sit on disk together for long. Note that temp() only fires for consumers actually
# in the DAG: a partial target such as `snakemake chemical` does not pull this rule in, so partial
# builds leave their .txt files in place.
#
# There is deliberately no uncompress_compendium_file counterpart: a wildcard .txt.gz -> .txt rule
# alongside this wildcard .txt -> .txt.gz one would be mutually satisfiable and risks an
# AmbiguousRuleException. Use `gunzip -k` by hand if you need a .txt back from a finished build.
rule compress_compendium:
    input:
        compendium=config["output_directory"] + "/compendia/{filename}.txt",
        # Every job that reads an uncompressed compendium, so that temp() can reclaim the .txt
        # the moment this rule finishes.
        outputs_done=config["output_directory"] + "/reports/outputs_done",
        duckdb_done=config["output_directory"] + "/duckdb/done",
        kgx_done=config["output_directory"] + "/kgx/done",
        # The individual content reports rather than reports/reports_done, so that
        # check_compendia_gzipped_files can depend on this rule's output without a cycle.
        content_reports=expand(
            "{od}/reports/content/compendia/{stem}.json",
            od=config["output_directory"],
            stem=[os.path.splitext(fn)[0] for fn in get_all_compendia(config)],
        ),
    output:
        gzipped=config["output_directory"] + "/compendia/{filename}.txt.gz",
    benchmark:
        config["output_directory"] + "/benchmarks/compress_compendium_{filename}.tsv"
    resources:
        # Single-threaded stdlib gzip; Protein.txt is the worst case. Matches the budget
        # `rule protein` already carries for the comparable synonyms compression.
        runtime="6h",
    run:
        # gzip_files() is the stdlib gzip module, so this is single-threaded, and all 25 of these
        # jobs sit at the tail of the DAG. If that tail dominates wall-clock time, switch to pigz:
        # it is multi-threaded and its output is standard gzip, so no consumer changes. Check
        # benchmarks/compress_compendium_Protein.tsv after a full cluster run before deciding.
        # See https://github.com/NCATSTranslator/Babel/issues/946.
        util.gzip_files([input.compendium])
