blank_issues_enabled: true
contact_links:
  - name: How to file a good issue
    url: https://github.com/NCATSTranslator/Babel/blob/HEAD/docs/NewIssue.md
    about: Guidance on what to include and how to fill in the project fields
  - name: Babel documentation
    url: https://github.com/NCATSTranslator/Babel#readme
    about: General documentation and entry point for the project
