blank_issues_enabled: true
contact_links:
  - name: How to report and track issues
    url: https://github.com/NCATSTranslator/Babel/blob/HEAD/docs/Triage.md#part-1-reporting-and-tracking-issues-for-users
    about: Guidance on reporting issues effectively
  - name: Babel documentation
    url: https://github.com/NCATSTranslator/Babel#readme
    about: General documentation and entry point for the project
