#
# prefix_comparison.py
#
# Compare the current build's combined prefix report against a previous release's committed prefix
# report (`releases/prefix_reports/<version>.json`) and emit human-readable comparison tables. This
# replaces the manual step of loading two prefix reports into babel-validation's PrefixComparator.
#
# Like report_tables.py, this module calculates no new graph numbers -- it summarizes the JSON reports
# generated by `generate_prefix_report` in `src/reports/duckdb_reports.py`. Both sides share the
# combined schema {name, count_curies, count_cliques, by_clique, by_curie_prefix}, so the comparison
# reads the exact occurrence counts (by_file / count_curies) directly. count_cliques is approximate
# (HyperLogLog), which the report notes.
#
# Two tables are produced (mirroring PrefixComparator):
#   1. Overall diffs: All CURIEs, All cliques, then per-compendium-filename CURIE totals.
#   2. By-prefix-within-clique diffs: one row per (filename, clique_leader_prefix, curie_prefix),
#      sorted by absolute change (largest first, ignoring sign).
#
import csv
import datetime
import json
import os
import re
from collections import defaultdict
from pathlib import Path

from src.util import get_logger

logger = get_logger(__name__)

# Release names look like "2025jan23", "2025mar31", "2025sep1": a 4-digit year, a 3-letter lowercased
# month abbreviation, and a 1-or-2-digit day. We parse these into real dates because a lexical sort of
# the names is wrong (e.g. "dec" < "sep" alphabetically, but December is later than September).
_MONTH_ABBREVS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}
_RELEASE_NAME_RE = re.compile(r"^(\d{4})([a-z]{3})(\d{1,2})$")


def parse_release_date(name: str) -> datetime.date:
    """Parse a ``YYYYmonDD`` release name (e.g. ``2025sep1``) into a ``datetime.date``.

    :raises ValueError: if ``name`` is not a recognizable release name.
    """
    match = _RELEASE_NAME_RE.match(name)
    if not match:
        raise ValueError(f"Release name {name!r} is not of the form YYYYmonDD (e.g. '2025sep1').")
    year, month_abbrev, day = match.group(1), match.group(2), match.group(3)
    if month_abbrev not in _MONTH_ABBREVS:
        raise ValueError(f"Release name {name!r} has an unknown month abbreviation {month_abbrev!r}.")
    return datetime.date(int(year), _MONTH_ABBREVS[month_abbrev], int(day))


def list_release_names(baselines_dir: str) -> list[str]:
    """Return the release names (JSON stems) present in ``baselines_dir``, sorted oldest to newest by
    parsed release date.

    Files whose stem doesn't even *look* like a release name (``YYYYmonDD``) are skipped with a
    warning -- e.g. ``README.json``. A stem that matches the shape but is not a valid release date
    (a bad month like ``2025xyz1`` or an impossible day like ``2025feb31``) raises instead of being
    skipped: silently dropping it could hide the newest committed baseline and defeat the
    ``previous_release`` pin guard, so it must surface immediately.

    :raises ValueError: if a ``.json`` stem matches the release-name shape but is not a valid date.
    """
    names = []
    for entry in os.listdir(baselines_dir):
        if not entry.endswith(".json"):
            continue
        stem = entry[: -len(".json")]
        if not _RELEASE_NAME_RE.match(stem):
            logger.warning(f"Skipping non-release-named baseline {entry!r} in {baselines_dir}.")
            continue
        # Matches the YYYYmonDD shape but has a bad month/day: let parse_release_date raise rather than
        # silently hide a committed baseline from the "newest baseline" guard.
        parse_release_date(stem)
        names.append(stem)
    return sorted(names, key=parse_release_date)


def _load_report(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def _per_filename_curie_totals(report: dict) -> dict:
    """Sum by_clique[*].by_file[filename][*] into a {filename: total occurrence count} map (exact)."""
    totals = defaultdict(int)
    for leader_entry in report.get("by_clique", {}).values():
        for filename, curie_prefix_counts in leader_entry.get("by_file", {}).items():
            totals[filename] += sum(curie_prefix_counts.values())
    return dict(totals)


def _by_clique_prefix_counts(report: dict) -> dict:
    """Flatten by_clique into {(filename, clique_leader_prefix, curie_prefix): count} (exact)."""
    counts = {}
    for clique_leader_prefix, leader_entry in report.get("by_clique", {}).items():
        for filename, curie_prefix_counts in leader_entry.get("by_file", {}).items():
            for curie_prefix, count in curie_prefix_counts.items():
                counts[(filename, clique_leader_prefix, curie_prefix)] = count
    return counts


def _change(prev: int, cur: int):
    """Return (absolute_change, percent_string) for a previous/current value pair.

    Percent is ``NEW`` when there was no previous value (avoids division by zero) and ``-100.0%`` when
    the value dropped to zero.
    """
    absolute = cur - prev
    if prev == 0:
        percent = "NEW" if cur != 0 else "0.0%"
    else:
        percent = f"{100.0 * absolute / prev:+.1f}%"
    return absolute, percent


def _summary_sentence(filename, clique_leader_prefix, curie_prefix, prev, cur):
    """Render the human phrasing, e.g.
    '8,443,204 fewer INCHIKEY identifiers in SmallMolecule cliques led by PUBCHEM.COMPOUND'."""
    where = f"{curie_prefix} identifiers in {filename} cliques led by {clique_leader_prefix}"
    if prev == 0:
        return f"{cur:,} new {where}"
    if cur == 0:
        return f"{prev:,} removed {where}"
    delta = cur - prev
    if delta == 0:
        return f"no change in {where}"
    direction = "more" if delta > 0 else "fewer"
    return f"{abs(delta):,} {direction} {where}"


def generate_prefix_comparison(
    current_prefix_report_json: str,
    baseline_json: str,
    out_overall_csv: str,
    out_by_clique_csv: str,
    out_md: str,
    warn_abs: int,
    warn_pct: float,
):
    """Compare the current prefix report against a baseline and write two CSVs plus a Markdown summary.

    :param current_prefix_report_json: The current build's combined prefix report.
    :param baseline_json: The previous release's committed prefix report
        (``releases/prefix_reports/<version>.json``). May be absent (first run) -- the comparison is
        then skipped gracefully with header-only CSVs so downstream rules stay green.
    :param out_overall_csv: Overall (All CURIEs / All cliques / per-filename CURIE totals) diff table.
    :param out_by_clique_csv: Per-(filename, clique_leader_prefix, curie_prefix) diff table, sorted by
        absolute change, largest first.
    :param out_md: Markdown summary naming the baseline and listing notable changes.
    :param warn_abs: Flag any by-clique-prefix row whose absolute CURIE change is >= this.
    :param warn_pct: Flag any by-clique-prefix row whose |percent change| is >= this.
    """
    current = _load_report(current_prefix_report_json)
    release_name = current.get("name", "current")

    for path in (out_overall_csv, out_by_clique_csv, out_md):
        Path(path).parent.mkdir(parents=True, exist_ok=True)

    overall_header = ["Metric", "Previous", "Current", "Absolute change", "Percent change"]
    by_clique_header = [
        "Filename",
        "Clique leader prefix",
        "CURIE prefix",
        "Previous",
        "Current",
        "Absolute change",
        "Percent change",
        "Summary",
    ]

    if not os.path.exists(baseline_json):
        logger.warning(f"No baseline found at {baseline_json}; writing empty comparison for {release_name}.")
        _write_csv(out_overall_csv, overall_header, [])
        _write_csv(out_by_clique_csv, by_clique_header, [])
        with open(out_md, "w") as f:
            f.write(f"# Prefix comparison: {release_name}\n\n")
            f.write(
                f"No prior baseline was found at `{baseline_json}`, so no comparison was generated. "
                f"This is expected on a first run or when `previous_release` points at a release that "
                f"is not committed in `releases/prefix_reports/`.\n"
            )
        return

    baseline = _load_report(baseline_json)
    baseline_name = baseline.get("name", Path(baseline_json).stem)

    # --- Table 1: overall diffs ---
    overall_rows = []
    for metric, prev, cur in _overall_metric_pairs(baseline, current):
        absolute, percent = _change(prev, cur)
        overall_rows.append([metric, prev, cur, absolute, percent])
    _write_csv(out_overall_csv, overall_header, overall_rows)

    # --- Table 2: by-clique-prefix diffs, sorted by absolute change (largest first) ---
    prev_counts = _by_clique_prefix_counts(baseline)
    cur_counts = _by_clique_prefix_counts(current)
    by_clique_rows = []
    notable = []
    for key in prev_counts.keys() | cur_counts.keys():
        filename, clique_leader_prefix, curie_prefix = key
        prev = prev_counts.get(key, 0)
        cur = cur_counts.get(key, 0)
        absolute, percent = _change(prev, cur)
        summary = _summary_sentence(filename, clique_leader_prefix, curie_prefix, prev, cur)
        row = [filename, clique_leader_prefix, curie_prefix, prev, cur, absolute, percent, summary]
        by_clique_rows.append(row)

        # A row is notable if it was removed entirely, if its absolute change is large, or if it
        # changed by a large percentage against a non-zero baseline. Each term earns its place:
        #   - is_large_pct requires prev > 0 so brand-new prefixes (infinite percent) are surfaced
        #     only via is_large_abs, not flooded in as tiny new entries.
        #   - is_removed is NOT redundant with is_large_pct: a removal is always -100%, so is_large_pct
        #     already catches it whenever warn_pct <= 100, but is_removed guarantees vanished prefixes
        #     surface even if warn_pct is set above 100 (a "flag only things that more-than-doubled"
        #     configuration). Don't collapse it into is_large_pct.
        # By design a small prefix that moves past warn_pct (including any removal) is notable -- that
        # is what warn_pct controls; raise it to quiet small proportional swings. The list can be long,
        # but the Markdown shows only the top 50 by absolute magnitude (the CSV keeps them all).
        is_removed = cur == 0
        is_large_abs = abs(absolute) >= warn_abs
        is_large_pct = prev > 0 and abs(100.0 * absolute / prev) >= warn_pct
        if is_removed or is_large_abs or is_large_pct:
            notable.append(row)

    by_clique_rows.sort(key=lambda r: abs(r[5]), reverse=True)
    _write_csv(out_by_clique_csv, by_clique_header, by_clique_rows)

    notable.sort(key=lambda r: abs(r[5]), reverse=True)
    _write_markdown(out_md, release_name, baseline_name, baseline_json, overall_rows, notable, warn_abs, warn_pct)


def _overall_metric_pairs(baseline: dict, current: dict):
    """Yield (metric_label, previous, current) triples for the overall table."""
    yield "All CURIEs", baseline.get("count_curies", 0), current.get("count_curies", 0)
    yield "All cliques (approx)", baseline.get("count_cliques", 0), current.get("count_cliques", 0)

    prev_by_file = _per_filename_curie_totals(baseline)
    cur_by_file = _per_filename_curie_totals(current)
    for filename in sorted(prev_by_file.keys() | cur_by_file.keys()):
        yield f"{filename} CURIEs", prev_by_file.get(filename, 0), cur_by_file.get(filename, 0)


def _write_csv(path: str, header: list, rows: list):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)


def _write_markdown(path, release_name, baseline_name, baseline_json, overall_rows, notable, warn_abs, warn_pct):
    with open(path, "w") as f:
        f.write(f"# Prefix comparison: {release_name} vs {baseline_name}\n\n")
        f.write(
            f"Compared release `{release_name}` against baseline `{baseline_name}` "
            f"(`{baseline_json}`). One or more releases may have been skipped between them; this "
            f"report always compares against the `previous_release` pinned in `config.yaml`.\n\n"
        )
        f.write(
            "CURIE occurrence counts are exact; clique counts (and any distinct counts) are "
            "approximate (HyperLogLog, ~2% error), so treat small clique-count changes as noise.\n\n"
        )

        f.write("## Overall changes\n\n")
        f.write("| Metric | Previous | Current | Absolute change | Percent change |\n")
        f.write("| --- | ---: | ---: | ---: | ---: |\n")
        for metric, prev, cur, absolute, percent in overall_rows:
            f.write(f"| {metric} | {prev:,} | {cur:,} | {absolute:+,} | {percent} |\n")
        f.write("\n")

        f.write("## Notable changes\n\n")
        f.write(
            f"Rows removed entirely, or with an absolute change >= {warn_abs:,} or a percentage change "
            f">= {warn_pct}%, largest absolute change first.\n\n"
        )
        if not notable:
            f.write("No notable changes.\n\n")
        else:
            shown = notable[:50]
            for row in shown:
                _filename, _leader, _curie, _prev, _cur, absolute, percent, summary = row
                f.write(f"- {summary} ({absolute:+,}, {percent})\n")
            if len(notable) > len(shown):
                f.write(f"\n...and {len(notable) - len(shown)} more (see the CSV).\n")
        f.write("\n")

        f.write("## Full detail\n\n")
        f.write("- `prefix_comparison_overall.csv`\n")
        f.write("- `prefix_comparison_by_clique_prefix.csv`\n")
