# Kubernetes file for setting up a volume to use for Babel outputs.
#
# As of April 2023, Babel outputs take up around 200G, including
# intermediate files (~50G), compendia (~30G) and synonyms (over 100 GB).
# So 300G is probably enough.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: babel-outputs
  labels:
    app: babel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  storageClassName: basic
