"""Measure what DOID's overused xref targets do to disease clique sizes.

Two outputs, both regenerated by running this script:

* ``overused-targets.csv`` -- every xref target in DOID's concord claimed by two or more DOID
  subjects, most-claimed first. This is the exhaustive record; the Markdown report samples it.
* a summary table on stdout -- clique statistics with and without DOID in
  ``OVERUSE_FILTERED_CONCORDS``, which is the change this measurement justifies.

The clique numbers come from replaying the production ``compute_cliques_for_impact_report()``
over a finished build's ``intermediate/disease/`` rather than rebuilding, so they cannot drift
from what the pipeline does (see docs/sources/CLAUDE.md, "Replaying a pipeline function beats
rebuilding to measure a change"). A replay only sees the cliques the build already produced, so
it cannot show cliques that move *between* compendia -- confirm with ``babel-clique-diff`` on a
real build before trusting the totals.

Usage (needs a local or downloaded disease intermediate set):

    uv run python docs/sources/DOID/overused-xrefs/scripts/measure_overused_xrefs.py \
        [--intermediate-root babel_outputs/intermediate]
"""

import argparse
import collections
import csv
import glob
import os

import src.createcompendia.diseasephenotype as dp

# Cliques probed individually in the report. Each is the preferred identifier of a clique that
# one ICD-10 code inflated; the label is MONDO's.
PROBES = {
    "MONDO:0019064": "hereditary spastic paraplegia",
    "MONDO:0000912": "autosomal recessive nonsyndromic hearing loss 5",
    "MONDO:0000910": "retinitis pigmentosa 6",
}

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def tabulate_overused_targets(doid_concord, outfile):
    """Write every DOID xref target claimed by 2+ subjects to ``outfile`` as CSV."""
    subjects = collections.defaultdict(set)
    with open(doid_concord) as inf:
        for line in inf:
            subject, _predicate, target = line.rstrip("\n").split("\t")
            subjects[target].add(subject)
    overused = sorted(((t, s) for t, s in subjects.items() if len(s) > 1), key=lambda kv: (-len(kv[1]), kv[0]))
    with open(outfile, "w", newline="") as out:
        writer = csv.writer(out)
        writer.writerow(["target", "target_prefix", "doid_subject_count", "doid_subjects"])
        for target, subs in overused:
            writer.writerow([target, target.split(":")[0], len(subs), "|".join(sorted(subs))])
    return overused


def clique_stats(concords, ids):
    """Replay the production clique builder and summarize the clique-size distribution."""
    dicts, _types = dp.compute_cliques_for_impact_report(concords, ids)
    sizes = sorted((len(c) for c in {frozenset(v) for v in dicts.values()}), reverse=True)
    stats = {
        "identifiers": len(dicts),
        "cliques": len(sizes),
        "largest clique": sizes[0],
        "cliques >= 50 ids": len([s for s in sizes if s >= 50]),
        "cliques >= 20 ids": len([s for s in sizes if s >= 20]),
    }
    stats.update({f"{label} ({probe})": len(dicts.get(probe, {probe})) for probe, label in PROBES.items()})
    return stats


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--intermediate-root", default="babel_outputs/intermediate")
    args = parser.parse_args()

    root = os.path.join(args.intermediate_root, "disease")
    concords = sorted(p for p in glob.glob(f"{root}/concords/*") if not os.path.basename(p).startswith("metadata"))
    ids = sorted(glob.glob(f"{root}/ids/*"))
    doid_concord = os.path.join(root, "concords", "DOID")

    targets_csv = os.path.join(HERE, "overused-targets.csv")
    overused = tabulate_overused_targets(doid_concord, targets_csv)
    prefixes = collections.Counter(t.split(":")[0] for t, _ in overused)
    print(f"wrote {targets_csv}: {len(overused)} overused targets, by prefix {dict(prefixes.most_common(6))}\n")

    # Measure with DOID filtered and unfiltered. OVERUSE_FILTERED_CONCORDS is read at glom time,
    # so toggling it here exercises exactly the production code path.
    unfiltered = dp.OVERUSE_FILTERED_CONCORDS - {"DOID"}
    filtered = dp.OVERUSE_FILTERED_CONCORDS | {"DOID"}
    dp.OVERUSE_FILTERED_CONCORDS = unfiltered
    before = clique_stats(concords, ids)
    dp.OVERUSE_FILTERED_CONCORDS = filtered
    after = clique_stats(concords, ids)

    width = max(len(k) for k in before)
    print(f"{'':{width}}  {'DOID unfiltered':>16}  {'DOID filtered':>14}")
    for key in before:
        print(f"{key:{width}}  {before[key]:>16,}  {after[key]:>14,}")


if __name__ == "__main__":
    main()
